import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-healthcare-coordination-benefits-recovery",
  "engine": "recovery",
  "title": "Healthcare Coordination of Benefits Recovery",
  "shortTitle": "Healthcare Coordination of Benefits Recovery",
  "tagline": "Identify claims where another payer was primary and execute compliant recovery or rebilling workflows.",
  "industry": "Payer Payment Integrity",
  "buyer": "Health plans and third-party administrators",
  "uiPort": 4648,
  "apiPort": 5648,
  "accent": "#4338ca",
  "currency": "USD",
  "primaryOutcome": "Healthcare Coordination of Benefits Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect member coverage, questionnaires, Medicare data, employer plans, accident details, claims, EOBs, payer order rules, recoveries, and correspondence in one accountable workflow. Identify claims where another payer was primary and execute compliant recovery or rebilling workflows.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Healthcare Coordination of Benefits Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("member-coverage-registry","HCB01","Member coverage registry","Execute member coverage registry using member coverage, questionnaires, Medicare data, employer plans, accident details, claims, EOBs, payer order rules, recoveries, and correspondence.","Produce a governed member coverage registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Claim Population","text","Member / Claim Population · Standard Case"],["caseReference","Member coverage registry Reference","text","HCB01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",576250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",697263],["domainDriver","Other Coverage","select","Employer plan",["Employer plan","Medicare","Liability carrier"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member coverage registry case","COB questionnaire workflow case","Medicare eligibility matching case","Employer plan matching case","Dependent birthday rule case"]}),
feature("cob-questionnaire-workflow","HCB02","COB questionnaire workflow","Execute cob questionnaire workflow using member coverage, questionnaires, Medicare data, employer plans, accident details, claims, EOBs, payer order rules, recoveries, and correspondence.","Produce a governed cob questionnaire workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Claim Population","text","Member / Claim Population · Standard Case"],["caseReference","COB questionnaire workflow Reference","text","HCB02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",576250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",697263],["domainDriver","Other Coverage","select","Employer plan",["Employer plan","Medicare","Liability carrier"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member coverage registry case","COB questionnaire workflow case","Medicare eligibility matching case","Employer plan matching case","Dependent birthday rule case"]}),
feature("medicare-eligibility-matching","HCB03","Medicare eligibility matching","Execute medicare eligibility matching using member coverage, questionnaires, Medicare data, employer plans, accident details, claims, EOBs, payer order rules, recoveries, and correspondence.","Produce a governed medicare eligibility matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Claim Population","text","Member / Claim Population · Standard Case"],["caseReference","Medicare eligibility matching Reference","text","HCB03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",576250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",697263],["domainDriver","Other Coverage","select","Employer plan",["Employer plan","Medicare","Liability carrier"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member coverage registry case","COB questionnaire workflow case","Medicare eligibility matching case","Employer plan matching case","Dependent birthday rule case"]}),
feature("employer-plan-matching","HCB04","Employer plan matching","Execute employer plan matching using member coverage, questionnaires, Medicare data, employer plans, accident details, claims, EOBs, payer order rules, recoveries, and correspondence.","Produce a governed employer plan matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Claim Population","text","Member / Claim Population · Standard Case"],["caseReference","Employer plan matching Reference","text","HCB04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",576250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",697263],["domainDriver","Other Coverage","select","Employer plan",["Employer plan","Medicare","Liability carrier"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member coverage registry case","COB questionnaire workflow case","Medicare eligibility matching case","Employer plan matching case","Dependent birthday rule case"]}),
feature("dependent-birthday-rule","HCB05","Dependent birthday rule","Execute dependent birthday rule using member coverage, questionnaires, Medicare data, employer plans, accident details, claims, EOBs, payer order rules, recoveries, and correspondence.","Produce a governed dependent birthday rule decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Claim Population","text","Member / Claim Population · Standard Case"],["caseReference","Dependent birthday rule Reference","text","HCB05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",576250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",697263],["domainDriver","Other Coverage","select","Employer plan",["Employer plan","Medicare","Liability carrier"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member coverage registry case","COB questionnaire workflow case","Medicare eligibility matching case","Employer plan matching case","Dependent birthday rule case"]}),
feature("working-aged-rules","HCB06","Working-aged rules","Execute working-aged rules using member coverage, questionnaires, Medicare data, employer plans, accident details, claims, EOBs, payer order rules, recoveries, and correspondence.","Produce a governed working-aged rules decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Claim Population","text","Member / Claim Population · Standard Case"],["caseReference","Working-aged rules Reference","text","HCB06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",576250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",697263],["domainDriver","Other Coverage","select","Employer plan",["Employer plan","Medicare","Liability carrier"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member coverage registry case","COB questionnaire workflow case","Medicare eligibility matching case","Employer plan matching case","Dependent birthday rule case"]}),
feature("disability-esrd-rules","HCB07","Disability ESRD rules","Execute disability esrd rules using member coverage, questionnaires, Medicare data, employer plans, accident details, claims, EOBs, payer order rules, recoveries, and correspondence.","Produce a governed disability esrd rules decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Claim Population","text","Member / Claim Population · Standard Case"],["caseReference","Disability ESRD rules Reference","text","HCB07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",576250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",697263],["domainDriver","Other Coverage","select","Employer plan",["Employer plan","Medicare","Liability carrier"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member coverage registry case","COB questionnaire workflow case","Medicare eligibility matching case","Employer plan matching case","Dependent birthday rule case"]}),
feature("accident-liability-detection","HCB08","Accident liability detection","Execute accident liability detection using member coverage, questionnaires, Medicare data, employer plans, accident details, claims, EOBs, payer order rules, recoveries, and correspondence.","Produce a governed accident liability detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Claim Population","text","Member / Claim Population · Standard Case"],["caseReference","Accident liability detection Reference","text","HCB08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",576250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",697263],["domainDriver","Other Coverage","select","Employer plan",["Employer plan","Medicare","Liability carrier"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member coverage registry case","COB questionnaire workflow case","Medicare eligibility matching case","Employer plan matching case","Dependent birthday rule case"]}),
feature("claim-payer-order-calculation","HCB09","Claim payer-order calculation","Execute claim payer-order calculation using member coverage, questionnaires, Medicare data, employer plans, accident details, claims, EOBs, payer order rules, recoveries, and correspondence.","Produce a governed claim payer-order calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Claim Population","text","Member / Claim Population · Standard Case"],["caseReference","Claim payer-order calculation Reference","text","HCB09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",576250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",697263],["domainDriver","Other Coverage","select","Employer plan",["Employer plan","Medicare","Liability carrier"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member coverage registry case","COB questionnaire workflow case","Medicare eligibility matching case","Employer plan matching case","Dependent birthday rule case"]}),
feature("overpayment-identification","HCB10","Overpayment identification","Execute overpayment identification using member coverage, questionnaires, Medicare data, employer plans, accident details, claims, EOBs, payer order rules, recoveries, and correspondence.","Produce a governed overpayment identification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Claim Population","text","Member / Claim Population · Standard Case"],["caseReference","Overpayment identification Reference","text","HCB10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",576250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",697263],["domainDriver","Other Coverage","select","Employer plan",["Employer plan","Medicare","Liability carrier"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member coverage registry case","COB questionnaire workflow case","Medicare eligibility matching case","Employer plan matching case","Dependent birthday rule case"]}),
feature("provider-recovery-notice","HCB11","Provider recovery notice","Execute provider recovery notice using member coverage, questionnaires, Medicare data, employer plans, accident details, claims, EOBs, payer order rules, recoveries, and correspondence.","Produce a governed provider recovery notice decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Claim Population","text","Member / Claim Population · Standard Case"],["caseReference","Provider recovery notice Reference","text","HCB11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",576250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",697263],["domainDriver","Other Coverage","select","Employer plan",["Employer plan","Medicare","Liability carrier"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member coverage registry case","COB questionnaire workflow case","Medicare eligibility matching case","Employer plan matching case","Dependent birthday rule case"]}),
feature("primary-payer-rebilling","HCB12","Primary payer rebilling","Execute primary payer rebilling using member coverage, questionnaires, Medicare data, employer plans, accident details, claims, EOBs, payer order rules, recoveries, and correspondence.","Produce a governed primary payer rebilling decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Claim Population","text","Member / Claim Population · Standard Case"],["caseReference","Primary payer rebilling Reference","text","HCB12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",576250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",697263],["domainDriver","Other Coverage","select","Employer plan",["Employer plan","Medicare","Liability carrier"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member coverage registry case","COB questionnaire workflow case","Medicare eligibility matching case","Employer plan matching case","Dependent birthday rule case"]}),
feature("member-appeal-evidence","HCB13","Member appeal evidence","Execute member appeal evidence using member coverage, questionnaires, Medicare data, employer plans, accident details, claims, EOBs, payer order rules, recoveries, and correspondence.","Produce a governed member appeal evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Claim Population","text","Member / Claim Population · Standard Case"],["caseReference","Member appeal evidence Reference","text","HCB13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",576250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",697263],["domainDriver","Other Coverage","select","Employer plan",["Employer plan","Medicare","Liability carrier"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member coverage registry case","COB questionnaire workflow case","Medicare eligibility matching case","Employer plan matching case","Dependent birthday rule case"]}),
feature("recovery-cash-ledger","HCB14","Recovery cash ledger","Execute recovery cash ledger using member coverage, questionnaires, Medicare data, employer plans, accident details, claims, EOBs, payer order rules, recoveries, and correspondence.","Produce a governed recovery cash ledger decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Claim Population","text","Member / Claim Population · Standard Case"],["caseReference","Recovery cash ledger Reference","text","HCB14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",576250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",697263],["domainDriver","Other Coverage","select","Employer plan",["Employer plan","Medicare","Liability carrier"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member coverage registry case","COB questionnaire workflow case","Medicare eligibility matching case","Employer plan matching case","Dependent birthday rule case"]}),
feature("cob-root-cause-analytics","HCB15","COB root-cause analytics","Execute cob root-cause analytics using member coverage, questionnaires, Medicare data, employer plans, accident details, claims, EOBs, payer order rules, recoveries, and correspondence.","Produce a governed cob root-cause analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Member / Claim Population","text","Member / Claim Population · Standard Case"],["caseReference","COB root-cause analytics Reference","text","HCB15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",576250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",697263],["domainDriver","Other Coverage","select","Employer plan",["Employer plan","Medicare","Liability carrier"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Member coverage registry case","COB questionnaire workflow case","Medicare eligibility matching case","Employer plan matching case","Dependent birthday rule case"]})
]);
